version: "3"

# config https so funcinou depois de seguir o passo a passo:
# dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p SuperSecretPassword
# dotnet dev-certs https --trust
# Link: https://github.com/aspnetrun/run-aspnetcore-microservices/issues/85

services:
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: my_db
      MONGO_INITDB_ROOT_USERNAME: teste
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongodbvolume:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 512mb

  webapi:
    container_name: FinanMapApi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 206mb
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 7171:8081
      - 7170:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_Kestrel__Certificates__Default__Password: SuperSecretPassword
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      MONGO_URL: "mongodb://teste:123456@mongodb:27017"
      Email_SMTP: ""
      Password_SMTP: ""
      JWT_KEY: ""
      JWT_ISSUER: ""
      JWT_AUDIENCE: ""

volumes:
  mongodbvolume:
    name: mongodbVolume
    driver: local
